#!/usr/bin/env python3
"""Release helper functions shared by GitHub Actions and tests."""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path


PROJECT_NAME = "HunterX"
SEMVER_RE = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")


def is_valid_semver(version: str) -> bool:
    """Return True for strict x.y.z SemVer used by HunterX releases."""
    return bool(SEMVER_RE.fullmatch(version.strip()))


def validate_semver(version: str) -> str:
    """Return a normalized version or raise ValueError."""
    normalized = version.strip()
    if not is_valid_semver(normalized):
        raise ValueError(f"Invalid release version: {version!r}. Expected strict SemVer like 0.1.0.")
    return normalized


def resolve_version(event_name: str, ref_name: str, input_version: str | None = None) -> str:
    """Resolve and validate a release version from a tag push or workflow_dispatch input."""
    if event_name == "workflow_dispatch":
        if input_version is None or not input_version.strip():
            raise ValueError("workflow_dispatch requires a version input such as 0.1.0.")
        if input_version.strip().startswith("v"):
            raise ValueError("workflow_dispatch version must not include a leading v.")
        return validate_semver(input_version)

    if not ref_name.startswith("v"):
        raise ValueError(f"Tag release must use v-prefixed refs such as v0.1.0, got {ref_name!r}.")
    return validate_semver(ref_name[1:])


def artifact_name(version: str, platform: str = "windows") -> str:
    """Return the release ZIP name for a platform."""
    normalized = validate_semver(version)
    platform_slug = platform.strip().lower()
    if not re.fullmatch(r"[a-z0-9_]+", platform_slug):
        raise ValueError(f"Invalid platform slug: {platform!r}")
    return f"hunterX_{platform_slug}_{normalized}.zip"


def source_archive_prefix(version: str) -> str:
    """Return the single top-level directory used inside source archives."""
    return f"hunterX-{validate_semver(version)}/"


def project_version(metadata_path: Path) -> str:
    """Read the literal APP_VERSION assignment without importing project code."""
    try:
        source = metadata_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValueError(f"Unable to read project metadata {metadata_path}: {exc}") from exc

    try:
        module = ast.parse(source, filename=str(metadata_path))
    except SyntaxError as exc:
        raise ValueError(f"Invalid Python syntax in project metadata {metadata_path}: {exc}") from exc

    assignments: list[ast.AST | None] = []
    for node in module.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "APP_VERSION" for target in node.targets
        ):
            assignments.append(node.value)
        elif (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "APP_VERSION"
        ):
            assignments.append(node.value)

    if len(assignments) != 1:
        raise ValueError(
            f"Expected exactly one top-level APP_VERSION assignment in {metadata_path}, "
            f"found {len(assignments)}."
        )

    value_node = assignments[0]
    if not isinstance(value_node, ast.Constant) or not isinstance(value_node.value, str):
        raise ValueError(f"APP_VERSION in {metadata_path} must be a literal string.")
    normalized = validate_semver(value_node.value)
    if normalized != value_node.value:
        raise ValueError(f"APP_VERSION in {metadata_path} must not contain surrounding whitespace.")
    return normalized


def validate_project_version(version: str, metadata_path: Path) -> str:
    """Require a requested release version to match project metadata exactly."""
    requested = validate_semver(version)
    declared = project_version(metadata_path)
    if requested != declared:
        raise ValueError(
            f"Release version mismatch: requested {requested}, "
            f"but {metadata_path} declares APP_VERSION {declared}."
        )
    return declared


def extract_changelog(version: str, changelog_path: Path) -> str:
    """Extract a matching CHANGELOG.md section, with a non-failing fallback."""
    normalized = validate_semver(version)
    fallback = (
        f"## {PROJECT_NAME} v{normalized}\n\n"
        "- Windows build artifact generated by the HunterX release workflow.\n"
        "- See CHANGELOG.md for project history."
    )
    if not changelog_path.exists():
        return fallback

    content = changelog_path.read_text(encoding="utf-8", errors="replace")
    headings = list(re.finditer(r"(?m)^##\s+(.+?)\s*$", content))
    for index, match in enumerate(headings):
        title = match.group(1).strip()
        title_version = title[1:] if title.startswith("v") else title
        if title_version == normalized:
            start = match.end()
            end = headings[index + 1].start() if index + 1 < len(headings) else len(content)
            section = content[start:end].strip()
            if section:
                return section
    return fallback


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="HunterX release utility")
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate_parser = subparsers.add_parser("validate")
    validate_parser.add_argument("--version", required=True)

    resolve_parser = subparsers.add_parser("resolve-version")
    resolve_parser.add_argument("--event-name", required=True)
    resolve_parser.add_argument("--ref-name", required=True)
    resolve_parser.add_argument("--input-version", default="")

    artifact_parser = subparsers.add_parser("artifact-name")
    artifact_parser.add_argument("--version", required=True)
    artifact_parser.add_argument("--platform", default="windows")

    prefix_parser = subparsers.add_parser("source-prefix")
    prefix_parser.add_argument("--version", required=True)

    project_version_parser = subparsers.add_parser("project-version")
    project_version_parser.add_argument("--metadata", default="src/hunter_metadata.py")

    project_check_parser = subparsers.add_parser("validate-project-version")
    project_check_parser.add_argument("--version", required=True)
    project_check_parser.add_argument("--metadata", default="src/hunter_metadata.py")

    notes_parser = subparsers.add_parser("notes")
    notes_parser.add_argument("--version", required=True)
    notes_parser.add_argument("--changelog", default="CHANGELOG.md")

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)

    try:
        if args.command == "validate":
            print(validate_semver(args.version))
        elif args.command == "resolve-version":
            print(resolve_version(args.event_name, args.ref_name, args.input_version))
        elif args.command == "artifact-name":
            print(artifact_name(args.version, args.platform))
        elif args.command == "source-prefix":
            print(source_archive_prefix(args.version))
        elif args.command == "project-version":
            print(project_version(Path(args.metadata)))
        elif args.command == "validate-project-version":
            print(validate_project_version(args.version, Path(args.metadata)))
        elif args.command == "notes":
            print(extract_changelog(args.version, Path(args.changelog)))
        else:
            parser.error(f"Unhandled command: {args.command}")
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
