"""Project metadata for the HunterX fork."""

APP_NAME = "HunterX"
APP_VERSION = "0.4.2"
APP_DISPLAY_VERSION = f"{APP_NAME} ({APP_VERSION})"
REPOSITORY = "sssss928/hunterX"
REPOSITORY_URL = f"https://github.com/{REPOSITORY}"
RELEASE_URL = f"{REPOSITORY_URL}/releases"
ISSUES_URL = f"{REPOSITORY_URL}/issues"
UPSTREAM_REPOSITORY = "bouob/tickets_hunter"
UPSTREAM_REPOSITORY_URL = f"https://github.com/{UPSTREAM_REPOSITORY}"
